### ISSUE TITLE
System Restore Point in tweak section taking way too much

### ISSUE THREAD

**Issue by KRMX** [ChrisTitusTech/winutil#2704]
## Bug description
The script took more than 45 minutes to perform a system restore point (as I'm writing it is stuck on 99% for 20 minutes)
Looks like the progress bar went slower and slower the more it progressed.

## Steps to reproduce the behavior:
1. Go to Tweaks
2. Click on Create Restore Point (was enabled by default)
4. Click Run tweaks

## Expected behavior
Expected it would take same time as a system restore point created through windows UI

## Additional context
Got a warning saying Microsoft.PowerShell.Management not imported because it was already imported (Snap-in?)
The tweak I selected apart from system restore was the one for disabling telemetry
OS: Windows 10, version 1909

**Comment by ioannedelea** [comment]
The same behaviour on Windows 11 23H2 (build 22631.2861). The System Restore is stuck at 99% for about 30 mins now as I'm posting this.

**Comment by 4yman-0** [comment]
## It takes way too ***long***

>Got a warning saying Microsoft.PowerShell.Management not imported because it was already imported.

That's because of *this*:
```powershell
        # Attempt to load the required module for Get-ComputerRestorePoint
        try {
            Import-Module Microsoft.PowerShell.Management -ErrorAction Stop
        } catch {
            Write-Host "Failed to load the Microsoft.PowerShell.Management module: $_"
            return
        }
```

<br>

> The script took more than 45 minutes to perform a system restore point

 It looks like you have an HDD or a stupidly bloated Installation, I don't know if *this* is slower than Windows UI.
```powershell
        Checkpoint-Computer -Description $description -RestorePointType "MODIFY_SETTINGS"
```

**Comment by zdziejowski** [comment]
Three days ago, I installed Microwin, and after the installation, I installed a few applications using Winutil and applied some tweaks for laptop. Creating a restore point also took around 40 minutes through Winutil. Spec: Dell XPS, SSD M2, 32GB RAM

**Comment by HardCorePawn** [comment]
I am having the same issue... It speeds through the creation of the system restore point until around 90% (about 2-3 minutes total) and then each % point after that seems to take exponentially longer to finish.

98->99% took ~10-12 minutes... and it has now been stuck at 99% for over 45 minutes at this point.

**Comment by dbalcar** [comment]
I am seeing the same issue.  the creating restore point is stuck on 98% for the last 30 min.  I will run it without creating a restore point. Hopefully this is easy catch on the bug side.

**Comment by joshistoast** [comment]
Mine's been stuck at 99% for over an hour now. Fix plz.

**Comment by ghost** [comment]
fixed /close

**Comment by aaron-746** [comment]
I've been stuck on 99% for over 12 hours now, so not sure that qualifies as "fixed /close"?

**Comment by itamcampos** [comment]
> I've been stuck on 99% for over 12 hours now, so not sure that qualifies as "fixed /close"?

I'm experiencing the same behavior. I've been stuck at 99% for hours.

**Comment by Netrunner-Syscrash** [comment]
This is still an issue and worked better in previous versions. Currently I'm also stuck at 99%. I corrected my timezone - still the same issue on a SSD.
